export type Currency = {name: string; shorthand: string; symbol: string};

export const currencyList: Currency[] = [
  {name: 'Euro', shorthand: 'EUR', symbol: '€'},
  {name: 'US Dollar', shorthand: 'USD', symbol: '$'},
  {name: 'New Zealand Dollar', shorthand: 'NZD', symbol: '$'},
  {name: 'Australian Dollar', shorthand: 'AUD', symbol: '$'},
  {name: 'British Pound', shorthand: 'GBP', symbol: '£'},
  {name: 'Chinese Yuan', shorthand: 'CNY', symbol: '元'},
  {name: 'Japanese Yen', shorthand: 'YEN', symbol: '¥'},
  {name: 'Swiss Franc', shorthand: 'CHF', symbol: '€'},
  {name: 'Indian Rupee', shorthand: 'INR', symbol: '₹'},
  {name: 'Singapur Dollar', shorthand: 'SGD', symbol: '$'},
  {name: 'Swedish Krona', shorthand: 'SEK', symbol: 'kr'},
  {name: 'Norwegian Krona', shorthand: 'NOK', symbol: 'kr'},
  {name: 'Mexican Peso', shorthand: 'MXN', symbol: '$'},
  {name: 'Hong Kong Dollar', shorthand: 'HKD', symbol: '$'},
  {name: 'South Korean Won', shorthand: 'KRW', symbol: '₩'},
  {name: 'Turkish Lira', shorthand: 'TRY', symbol: '₺'},
  {name: 'South African Rand', shorthand: 'ZAR', symbol: 'R'},
  {name: 'Brazilian Real', shorthand: 'BRL', symbol: 'R$'},
  {name: 'Polish Złoty', shorthand: 'PLN', symbol: 'zł'},
  {name: 'Thai Baht', shorthand: 'THB', symbol: '฿'},
  {name: 'Malaysian Ringgit', shorthand: 'MYR', symbol: 'RM'},
  {name: 'Indonesian Rupiah', shorthand: 'IDR', symbol: 'Rp'},
  {name: 'Philippine Peso', shorthand: 'PHP', symbol: '₱'},
  {name: 'Israeli New Shekel', shorthand: 'ILS', symbol: '₪'},
  {name: 'Czech Koruna', shorthand: 'CZK', symbol: 'Kč'},
  {name: 'Hungarian Forint', shorthand: 'HUF', symbol: 'Ft'},
  {name: 'Chilean Peso', shorthand: 'CLP', symbol: '$'},
  {name: 'Egyptian Pound', shorthand: 'EGP', symbol: 'E£'},
  {name: 'Saudi Riyal', shorthand: 'SAR', symbol: '﷼'},
  {name: 'United Arab Emirates Dirham', shorthand: 'AED', symbol: 'د.إ'},
  {name: 'Argentine Peso', shorthand: 'ARS', symbol: '$'},
  {name: 'Colombian Peso', shorthand: 'COP', symbol: '$'},
  {name: 'Nigerian Naira', shorthand: 'NGN', symbol: '₦'},
  {name: 'Qatari Riyal', shorthand: 'QAR', symbol: '﷼'},
  {name: 'Kuwaiti Dinar', shorthand: 'KWD', symbol: 'د.ك'},
  {name: 'Omani Rial', shorthand: 'OMR', symbol: '﷼'},
  {name: 'Bahraini Dinar', shorthand: 'BHD', symbol: 'ب.د'},
  {name: 'Kazakhstani Tenge', shorthand: 'KZT', symbol: '₸'},
  {name: 'Bangladeshi Taka', shorthand: 'BDT', symbol: '৳'},
  {name: 'Vietnamese Dong', shorthand: 'VND', symbol: '₫'},
  {name: 'Romanian Leu', shorthand: 'RON', symbol: 'lei'},
  {name: 'Kenyan Shilling', shorthand: 'KES', symbol: 'KSh'},
  {name: 'Nepalese Rupee', shorthand: 'NPR', symbol: '₨'},
  {name: 'Sri Lankan Rupee', shorthand: 'LKR', symbol: '₨'},
  {name: 'Croatian Kuna', shorthand: 'HRK', symbol: 'kn'},
  {name: 'Uruguayan Peso', shorthand: 'UYU', symbol: '$U'},
  {name: 'Tunisian Dinar', shorthand: 'TND', symbol: 'د.ت'},
  {name: 'Guatemalan Quetzal', shorthand: 'GTQ', symbol: 'Q'},
  {name: 'Serbian Dinar', shorthand: 'RSD', symbol: 'дин.'},
  {name: 'Costa Rican Colón', shorthand: 'CRC', symbol: '₡'},
  {name: 'Icelandic Króna', shorthand: 'ISK', symbol: 'kr'},
  {name: 'Georgian Lari', shorthand: 'GEL', symbol: '₾'},
  {name: 'Paraguayan Guaraní', shorthand: 'PYG', symbol: '₲'},
  {name: 'Jordanian Dinar', shorthand: 'JOD', symbol: 'د.ا'},
  {name: 'Bulgarian Lev', shorthand: 'BGN', symbol: 'лв'},
  {name: 'Moroccan Dirham', shorthand: 'MAD', symbol: 'د.م.'},
  {name: 'Botswana Pula', shorthand: 'BWP', symbol: 'P'},
  {name: 'Ukrainian Hryvnia', shorthand: 'UAH', symbol: '₴'},
  {name: 'Mauritian Rupee', shorthand: 'MUR', symbol: '₨'},
  {name: 'Tanzanian Shilling', shorthand: 'TZS', symbol: 'TSh'},
  {name: 'Uzbekistani Som', shorthand: 'UZS', symbol: 'soʻm'},
  {name: 'Ghanaian Cedi', shorthand: 'GHS', symbol: '₵'},
  {name: 'Bolivian Boliviano', shorthand: 'BOB', symbol: 'Bs'},
  {name: 'Algerian Dinar', shorthand: 'DZD', symbol: 'د.ج'},
  {name: 'Macedonian Denar', shorthand: 'MKD', symbol: 'ден'},
  {name: 'Armenian Dram', shorthand: 'AMD', symbol: '֏'},
  {name: 'Nicaraguan Córdoba', shorthand: 'NIO', symbol: 'C$'},
  {name: 'Jamaican Dollar', shorthand: 'JMD', symbol: 'J$'},
  {name: 'Namibian Dollar', shorthand: 'NAD', symbol: 'N$'},
  {name: 'Moldovan Leu', shorthand: 'MDL', symbol: 'L'},
  {name: 'Honduran Lempira', shorthand: 'HNL', symbol: 'L'},
  {name: 'Haitian Gourde', shorthand: 'HTG', symbol: 'G'},
  {name: 'Rwandan Franc', shorthand: 'RWF', symbol: 'FRw'},
  {name: 'Cuban Peso', shorthand: 'CUP', symbol: '$MN'},
  {name: 'Surinamese Dollar', shorthand: 'SRD', symbol: '$'},
  {name: 'Malawian Kwacha', shorthand: 'MWK', symbol: 'MK'},
  {name: 'Zambian Kwacha', shorthand: 'ZMW', symbol: 'ZK'},
  {name: 'Lao Kip', shorthand: 'LAK', symbol: '₭'},
  {name: 'Fijian Dollar', shorthand: 'FJD', symbol: '$'},
  {name: 'Samoan Tala', shorthand: 'WST', symbol: 'T'},
  {name: 'Guyanese Dollar', shorthand: 'GYD', symbol: '$'},
  {name: 'Cape Verdean Escudo', shorthand: 'CVE', symbol: '$'},
  {name: 'Solomon Islands Dollar', shorthand: 'SBD', symbol: '$'},
  {name: 'Belize Dollar', shorthand: 'BZD', symbol: '$'},
  {name: 'Sierra Leonean Leone', shorthand: 'SLL', symbol: 'Le'},
  {name: 'Comorian Franc', shorthand: 'KMF', symbol: 'CF'},
  {name: 'Mauritanian Ouguiya', shorthand: 'MRU', symbol: 'UM'},
  {name: 'Malagasy Ariary', shorthand: 'MGA', symbol: 'Ar'},
  {name: 'Tajikistani Somoni', shorthand: 'TJS', symbol: 'ЅМ'},
  {name: 'Bahamian Dollar', shorthand: 'BSD', symbol: '$'},
  {name: 'Barbadian Dollar', shorthand: 'BBD', symbol: '$'},
  {name: 'Omani Rial', shorthand: 'OMR', symbol: '﷼'},
  {name: 'Falkland Islands Pound', shorthand: 'FKP', symbol: '£'},
  {name: 'Cayman Islands Dollar', shorthand: 'KYD', symbol: '$'},
  {name: 'Tongan Paʻanga', shorthand: 'TOP', symbol: 'T$'},
  {name: 'Seychellois Rupee', shorthand: 'SCR', symbol: '₨'},
  {name: 'Maldivian Rufiyaa', shorthand: 'MVR', symbol: 'ރ'},
  {name: 'Guyanese Dollar', shorthand: 'GYD', symbol: '$'},
  {name: 'Sudanese Pound', shorthand: 'SDG', symbol: 'ج.س.'},
  {name: 'Zimbabwean Dollar', shorthand: 'ZWL', symbol: 'Z$'},
  {name: 'Bhutanese Ngultrum', shorthand: 'BTN', symbol: 'Nu.'},
  {name: 'Aruban Florin', shorthand: 'AWG', symbol: 'ƒ'},
  {name: 'Gibraltar Pound', shorthand: 'GIP', symbol: '£'},
  {name: 'Surinamese Dollar', shorthand: 'SRD', symbol: '$'},
  {name: 'Lesotho Loti', shorthand: 'LSL', symbol: 'L'},
  {name: 'Mongolian Tögrög', shorthand: 'MNT', symbol: '₮'},
  {name: 'Somali Shilling', shorthand: 'SOS', symbol: 'S'},
  {name: 'Burundian Franc', shorthand: 'BIF', symbol: 'FBu'},
  {name: 'Gambian Dalasi', shorthand: 'GMD', symbol: 'D'},
  {name: 'Guinean Franc', shorthand: 'GNF', symbol: 'FG'},
  {name: 'Laotian Kip', shorthand: 'LAK', symbol: '₭'},
  {name: 'Mauritanian Ouguiya', shorthand: 'MRU', symbol: 'UM'},
  {name: 'Rwandan Franc', shorthand: 'RWF', symbol: 'FRw'},
];